name: Block merges from 'pruebas' to main or dev

on:
  pull_request:
    branches:
      - main
      - dev-api-task
      - dev

jobs:
  block-pruebas:
    if: github.head_ref == 'pruebas'
    runs-on: ubuntu-latest
    steps:
      - name: Block PR from 'pruebas' branch
        run: |
          echo "❌ Está prohibido hacer merge desde 'pruebas' a main o ramas de desarrollo (main, dev-api-task, dev). Cierra este PR y promueve cambios desde la rama de desarrollo correspondiente."
          exit 1